branches:
  only:
  - master
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
cache: pip
sudo: false
install: pip install -q -e .
script: python setup.py test
deploy:
  provider: pypi
  distributions: "sdist bdist bdist_wheel"
  user: m_messiah
  password:
    secure: MBzTUjw3FgzfV+WCudPjFdByamwWFxHRBLelZmXfrb2B/ne5l3D2hVdGTJTjUiletNKsB+XBRKQh3ehZ0wqnTN5mmQSwUu6rcv/xh939CRE5xZh2fJJQNFxzh5x/zb8LW2/yWZhbs2StimaQutKfnXg564gQjjtYsW5v04mBrDs=
